### PR TITLE
update: dependencies

### PR DESCRIPTION
**Pull request by Moamal-2000**
- Update project dependencies
- Improve accessibility
- Replace deprecated prop (layout)

### CODE REVIEW

**Review by mahmoud-saeed1 — COMMENTED** [review]
improve accessibilty

**Comment by mahmoud-saeed1** [comment]
improve accessibilty

**Comment by mahmoud-saeed1** [comment]
improve accessibilty

**Comment by Moamal-2000** [comment]
Hello @mahmoud-saeed1 

I wanted to let you know that I removed the forked repository, which automatically closed the pull request. I assumed you didn’t want the pull request to be merged into your repository, but you should still be able to view the changes I made. If you'd like, you can apply them to your project manually.

**Pull request closed without merging**
